background_color 1.80 1.00 0.60		R,G,B
mirror_color 0.48 0.33 0.23		R,G,B
floor_color 0.05 0.05 0.00		R,G,B
sunshine_color 0.48 0.33 0.23		R,G,B
ambient_color 0.96 0.66 0.46		R,G,B
fog_distance 150.00
sharp_shadow 1
sky_on 1
ambient_light_dir 0.00 0.00 1.00
sun_light_dir 0.00 0.00 1.00
sunbeam_color 0.00 0.00 0.00		B,G,R
sun_color 0.85 0.95 0.99		B,G,R
sky_color 0.25 0.25 0.30		B,G,R
polar_light_color 0.00 0.00 0.00	B,G,R
polar_light_dir 0.00 0.00 0.00
sky_blend_power 8.00
