background_color 0.00 0.00 0.00		R,G,B
mirror_color 0.10 0.10 0.10		R,G,B
floor_color 0.10 0.10 0.10		R,G,B
sunshine_color 1.00 1.00 1.00		R,G,B
ambient_color 1.00 1.00 1.00		R,G,B
fog_distance 80.00
sharp_shadow 1
sky_on 1
ambient_light_dir 0.00 -1.00 1.00
sun_light_dir 0.00 -1.00 1.00
sunbeam_color 1.00 1.00 1.00		B,G,R
sun_color 1.00 1.00 1.00		B,G,R
sky_color 0.50 0.50 0.50		B,G,R
polar_light_color 0.00 0.00 0.00	B,G,R
polar_light_dir 0.00 0.00 0.00
sky_blend_power 5.00
