background_color 0.85 0.40 0.30		R,G,B
mirror_color 0.06 0.12 0.00		R,G,B
floor_color 0.25 0.50 0.00		R,G,B
sunshine_color 0.80 0.70 0.00		R,G,B
ambient_color 0.60 0.35 0.30		R,G,B
fog_distance 50.00
sharp_shadow 1
sky_on 1
ambient_light_dir -5.00 0.00 0.40
sun_light_dir -5.00 0.00 0.40
sunbeam_color 0.30 0.99 1.00		B,G,R
sun_color 0.80 0.99 0.99		B,G,R
sky_color 0.35 0.40 0.30		B,G,R
polar_light_color 0.45 0.35 0.45	B,G,R
polar_light_dir 0.00 0.00 -1.00
