background_color 0.05 0.09 0.18		R,G,B
mirror_color 0.00 0.00 0.00		R,G,B
floor_color 0.20 0.30 0.10		R,G,B
sunshine_color 0.45 0.55 0.65		R,G,B
ambient_color 0.75 0.85 0.95		R,G,B
fog_distance 160.00
sharp_shadow 1
sky_on 1
ambient_light_dir 3.00 1.00 1.00
sun_light_dir 3.00 1.00 1.00
sunbeam_color 0.60 0.50 0.00		B,G,R
sun_color 0.99 1.05 1.00		B,G,R
sky_color 0.10 0.01 0.00		B,G,R
polar_light_color 0.00 0.00 0.00	B,G,R
polar_light_dir 0.00 0.00 0.00
sky_blend_power 3.00
