background_color 0.99 0.89 0.79		R,G,B
mirror_color 0.50 0.50 0.50		R,G,B
floor_color 0.60 0.50 0.40		R,G,B
sunshine_color 0.00 0.00 0.00		R,G,B
ambient_color 1.50 1.40 1.30		R,G,B
fog_distance 80.00
sharp_shadow 1
sky_on 1
ambient_light_dir -1.00 0.00 0.50
sun_light_dir -3.00 -5.00 1.00
sunbeam_color 0.25 0.40 0.50		B,G,R
sun_color 1.00 1.00 1.00		B,G,R
sky_color 0.85 0.80 0.82		B,G,R
polar_light_color 0.00 0.00 0.00	B,G,R
polar_light_dir 0.00 0.00 0.00
sky_blend_power 3.00
