background_color 0.80 0.50 0.10		R,G,B
mirror_color 0.05 0.03 0.01		R,G,B
floor_color 0.50 0.50 0.50		R,G,B
sunshine_color 0.90 0.80 0.20		R,G,B
ambient_color 1.80 1.50 1.10		R,G,B
fog_distance 80.00
sharp_shadow 1
sky_on 1
ambient_light_dir 0.00 -0.75 0.30
sun_light_dir -1.50 -0.75 0.30
sunbeam_color 1.20 1.80 1.90		B,G,R
sun_color 0.10 0.20 0.50		B,G,R
sky_color 0.05 0.05 0.10		B,G,R
polar_light_color 0.00 0.00 0.00	B,G,R
polar_light_dir 0.00 0.00 0.00
sky_blend_power 7.00
