background_color 0.55 0.54 0.50		R,G,B
mirror_color 0.20 0.20 0.20		R,G,B
floor_color 0.00 0.00 0.00		R,G,B
sunshine_color 0.20 0.20 0.20		R,G,B
ambient_color 0.75 0.75 0.75		R,G,B
fog_distance 30.00
sharp_shadow 1
sky_on 1
ambient_light_dir -5.00 0.80 0.60
sun_light_dir -5.00 0.80 0.60
sunbeam_color 0.08 0.10 0.10		B,G,R
sun_color 0.94 0.94 0.94		B,G,R
sky_color 0.80 0.80 0.80		B,G,R
polar_light_color 0.00 0.00 0.00	B,G,R
polar_light_dir 0.00 0.00 0.00
sky_blend_power 5.00
