background_color 0.95 0.75 0.18		R,G,B
mirror_color 0.00 0.00 0.00		R,G,B
floor_color 0.40 0.20 0.05		R,G,B
sunshine_color 1.00 0.80 0.15		R,G,B
ambient_color 1.00 0.80 0.15		R,G,B
fog_distance 80.00
sharp_shadow 1
sky_on 1
ambient_light_dir -3.00 2.00 1.25
sun_light_dir -3.00 2.00 1.25
sunbeam_color 0.45 0.70 0.99		B,G,R
sun_color 0.00 0.40 0.70		B,G,R
sky_color 0.15 0.35 0.80		B,G,R
polar_light_color 0.00 0.00 0.00	B,G,R
polar_light_dir 0.00 0.00 0.00
sky_blend_power 10.00
