background_color 0.50 0.20 0.05		R,G,B
mirror_color 0.50 0.50 0.50		R,G,B
floor_color 0.99 0.95 0.90		R,G,B
sunshine_color 0.99 0.85 0.55		R,G,B
ambient_color 0.50 0.30 0.07		R,G,B
fog_distance 87.40
sharp_shadow 1
sky_on 1
ambient_light_dir 0.00 -5.00 2.00
sun_light_dir 0.00 -5.00 2.00
sunbeam_color 0.55 0.85 0.99		B,G,R
sun_color 0.05 0.15 0.50		B,G,R
sky_color 0.30 0.50 0.60		B,G,R
polar_light_color 0.00 0.00 0.00	B,G,R
polar_light_dir 0.00 0.00 0.00
sky_blend_power 10.00
